import type { Metadata } from "next";
import "../globals.css";
import { AnnouncementBar, Footer, Header } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AnnouncementBar linkableAnnouncement />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
